---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице корзины пользователь cможет удалить товар из корзины
  - Со страницы корзины пользователь может вернуться на страниуц каталога и продолжить выбирать товары
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь может добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Сайт должен работать как SPA-приложение, которое не перезагружает страницу
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
implicit:
  - Корзина будет хранится в сессии браузера
  - Эксплуатация сайта должна соответствовать требованиям законодательства РФ
  - На сайте должна быть форма связи с технической поддержкой
  - На странице товара должна быть возможность оставлять отзыв о товаре
  - Пользователь не может изменять информацию о товаре
